---

nginx_user: nginx
nginx_group: "{{ nginx_user }}"
nginx_version: nginx-1.12.2
nginx_url: https://nginx.org/download/{{ nginx_version }}.tar.gz
nginx_spnego_repo: https://github.com/stnoonan/spnego-http-auth-nginx-module.git
nginx_path: /opt/nginx-spnego
nginx_sbin_path: /usr/sbin/nginx-spnego
nginx_conf_dir: /etc/nginx
nginx_log_dir: /var/log/nginx
nginx_pid_path: /var/run/nginx.pid
nginx_lock_path: /var/run/nginx.lock
nginx_modules_path: /usr/lib64/nginx/modules
nginx_build_params:
  # core parameters
  - --with-debug
  - --with-compat
  - --with-file-aio
  - --with-threads
  # modules
  - --with-mail_ssl_module
  - --with-http_addition_module
  - --with-http_auth_request_module
  - --with-http_dav_module
  - --with-http_flv_module
  - --with-http_gunzip_module
  - --with-http_gzip_static_module
  - --with-http_mp4_module
  - --with-http_random_index_module
  - --with-http_realip_module
  - --with-http_secure_link_module
  - --with-http_slice_module
  - --with-http_ssl_module
  - --with-http_stub_status_module
  - --with-http_sub_module
  - --with-http_v2_module
  - --with-stream_realip_module
  - --with-stream_ssl_module
  - --with-stream_ssl_preread_module
  - --with-google_perftools_module
  # extra modules
  - --with-http_xslt_module=dynamic
  - --with-http_image_filter_module=dynamic
  - --with-http_geoip_module=dynamic
  - --with-http_perl_module=dynamic
  - --with-mail=dynamic
  - --with-stream=dynamic
